spring:
  application:
    name: chat
  data:
    mongodb:
      host: localhost
      port: 27018
      username: root
      password: testpassword1234
      database: mongodb
      authentication-database: admin
      authSource: admin

server:
  port: 8081

auth:
  url: "http://localhost:30001/"
page:
  size: 100
url:
  server: "http://localhost:8080"
